### ISSUE TITLE
RangeError when serving Large (3.6GB) File

### ISSUE THREAD

**Issue by phelma** [zeit/serve#14]
node v6.5.0
Serving a 3.6GB File, shows up correctly in browser file list, when I try to download it I get a 500 and micro-list reports:

```
RangeError: File size is greater than possible Buffer: 0x7fffffff bytes
    at FSReqWrap.readFileAfterStat [as oncomplete] (fs.js:392:11)
```

**Comment by timneutkens** [comment]
This is most likely caused by reading the file to a buffer:
https://github.com/zeit/micro-list/blob/master/bin/list#L66
https://github.com/zeit/micro-list/blob/master/bin/list#L216
https://github.com/zeit/micro-list/blob/master/bin/list#L229

Might have to build in some stream support if possible. Micro-list is most likely not intended for this usage atm 😅

**Comment by leo** [comment]
This sounds like a good idea: https://github.com/pillarjs/send

**Comment by leo** [comment]
@phelma Please try if master works! https://github.com/zeit/list/commit/32306702d1f0d63ae8ec9cd126c2411712cdf2e0

**Comment by leo** [comment]
^

**Comment by phelma** [comment]
@leo working for me, thanks!
