### ISSUE TITLE
Send arguments via command line

### ISSUE THREAD

**Issue by OscarCanek** [zeit/serve#263]
How can I send arguments throught the command serve to use it with process.argv?
If not, there a way to do that?

**Comment by barinali** [comment]
@OscarCanek, could you explain the case a little more?

But before you explain it more, I'd like to explain what I got from the issue. If I didn't get it wrong, you want to run `serve --key=value`, and reach this `key`-`value` pair in your javascript files? If this is the case, I think it's not possible since `serve` is just a static file server.

**Comment by fmiras** [comment]
If the case is the explained by @barinali you should use serve programatically and make your own CLI with your custom flags, that's the reason of why serve can be used programatically, to not depend of the CLI and use an API.

**Comment by leo** [comment]
Correct ^ 😊
