### ISSUE TITLE
Using it with service worker and Create React App

### ISSUE THREAD

**Issue by jasan-s** [zeit/serve#268]
I can't seem to figure out how to set `max-age =0 `for the `serve-worker.js`  file. Because of caching the service never updates automatically.  `serve --cache 0 -s build` does not work

**Comment by 5c077yP** [comment]
@jasan-s i cannot confirm this. i had the same problem, but just needed to clear my chrome browser history. Then it worked.

**Comment by praveenweb** [comment]
@jasan-s I think when you are using ```serve --cache 0 -s build```, ```-s``` means that caching is enabled for one day. (you can look at serve --help for this information). Remove ```-s``` flag from your command caching will be disabled. But the problem is it will disable it for the all the files, including js and css, instead of just service-worker.js file.

**Comment by leo** [comment]
Thank you for the effort you've put into this!

This is now possible by supplying a `serve.json` file. All thanks to `serve-handler`, as described in the notes for the [new release](https://github.com/zeit/serve/releases/tag/7.0.0).

Simply add `headers` to your config file, as described in the `serve-handler` [documentation](https://github.com/zeit/serve-handler#headers-array).
