### ISSUE TITLE
Wrong mime-type for .wasm

### ISSUE THREAD

**Issue by mike1808** [zeit/serve#303]
Mime-type for `.wasm` should be `application/json`, but currently its `text/html`. It can be fixed by upgrading [mime-db](https://www.npmjs.com/package/mime-db) which is dependency of [mime-types](https://www.npmjs.com/package/mime-types). The current version (accroding to the lock file) is `1.30.0`

**Comment by leo** [comment]
Will update once the package update is out!

**Comment by philipp-spiess** [comment]
Quick update: Static files are served via [`send`](https://github.com/pillarjs/send/) which, instead of `mime-types`, uses [`mime`](https://github.com/broofa/node-mime) to determine the mime type (which again uses `mime-db`).

Now `mime` is [already updated](https://github.com/broofa/node-mime/commit/3f775bafa8bff0c1a4bd94bb07ab3065676e44f6) but `send` is not.

Here's the proper upstream issue to track: https://github.com/pillarjs/send/pull/154
