### ISSUE TITLE
i hope the serve can add proxy feture

### ISSUE THREAD

**Issue by xiyuyizhi** [zeit/serve#315]
i hope the serve can add proxy feture

eg: when request /api/users,serve  can proxy to other server

**Comment by leo** [comment]
Thank you for the effort you've put into this!

This is now possible by supplying a `serve.json` file. All thanks to `serve-handler`, as described in the notes for the [new release](https://github.com/zeit/serve/releases/tag/7.0.0).

Simply add `redirects` to your config file, as described in the `serve-handler` [documentation](https://github.com/zeit/serve-handler#headers-array).

**Comment by skipjack** [comment]
Those features are a little different than proxying though, right? I don't see a way with `rewrites` or `redirects` to actually serve responses from another server without returning a 301 or 302. It would be nice to be able to do something similar to an nginx reverse proxy.

**Comment by skipjack** [comment]
It seems this has actually been discussed and started here:

- https://github.com/zeit/serve-handler/issues/30
- https://github.com/zeit/serve-handler/pull/75

**Comment by nathancahill** [comment]
Yes, @leo please take a look at #75 which is a proxy implementation. A yes/no would be helpful. I'd like to maintain a public fork (currently using a private fork in production) if there's no interest in merging.

**Comment by x-yuri** [comment]
In my case I needed rewrites, and I must say trying to understand how this whole thing works is not easy. I couldn't figure out without looking into the source code. First I learned that `serve.json`'s path is resolved relative to the target (not current) directory. But the trickiest thing was specifying rewrites. It's not easy, unless there's an example for your case in the documentation. How exactly `path-to-regexp` and `minimatch` interact with each other, and all. Now I see that it's either many-to-one with `minimatch`, or one-to-one with `path-to-regexp`.

But in my case I needed many-to-many :) I needed to prefix the urls. That is, I wanted `serve assets` to do the following:

```
/assets/index.js -> /index.js
/assets/css/style.css -> /css/style.css
...
```

Like, `/assets/(.*)` -> `/$1`. One might say, I could just do `serve .`, but that would have made the `assets`' directory siblings available. The closest I could get to my goal is:

```json
{"rewrites": [
    {"source": "/assets/:path*", "destination": "/:path"}
]}
```

I was able get away with `/assets/:path*` owing to [this line][1]. It seems like it serves another purpose, but `/assets/:path*` gets transformed into `/assets/:path(.*)`, which is okay as long as `path-to-regexp` is concerned. The issue is with destination. When `:path` is interpolated, it is also [encoded][2]. So my `/`'s become `%2F`'s, and apparently it doesn't work:

```
/assets/css/style.css -> /css%2Fstyle.css
```

[1]: https://github.com/vercel/serve-handler/blob/6.1.3/src/index.js#L46
[2]: https://github.com/pillarjs/path-to-regexp/blob/v2.2.1/index.js#L177
