### ISSUE TITLE
--ssl more options

### ISSUE THREAD

**Issue by geniuscd** [zeit/serve#356]
Hey, `--ssl` will allow the https, but with self signed certificate.
another way is to allow to configure custom certificates by adding more options 
for example `--ssl-key` etc...

is there a roadmap to load custom certificates path?

**Comment by leo** [comment]
We've decided to not support SSL as a core feature anymore - in all cases there should be some form of proxy or load balancer on top to handle SSL, as there are simply too many variants.

I hope you understand!

Please also read the details about the [new release](https://github.com/zeit/serve/releases/tag/7.0.0).

**Comment by TomasHubelbauer** [comment]
Is there an alternative to `serve` which takes care of the self signed certificate out of the box? I use `npx serve .` in local development to serve contents of a directory, it would be great to have a similar tool which generates its own self-signed certificate automatically so that I could just run `npx serve . --ssl` and trust the certificate in the browser and be done with it.

**Comment by r0mflip** [comment]
**Shameless promition**: @TomasHubelbauer  https://github.com/ramlmn/serv
