### ISSUE TITLE
Why does serve silently check for updates?

### ISSUE THREAD

**Issue by Winona-Ryder** [zeit/serve#369]
It silently checks for updates in the background and I can't see this documented anywhere.

1. Why does it need to check for updates? this activity appears as a random internet connection where none was expected and gives off a spyware vibe (I know it's not, but that's the vibe it gives off).

2. Why isn't this documented anywhere (that I can find)?

3. How do I disable it?

Note: I didn't install the package manually, it came as dependency of other packages.

IMO, it should not be checking for updates by default, or at least not when the package is obviously not installed globally (which is a bad practice IMO).

**Comment by leo** [comment]
Sorry for the inconvience we've caused, but plenty of the command line interfaces installed on your device through npm are doing that.

We're simply using [update-check](https://github.com/zeit/update-check) to check for updates of the package, in order to keep it updated.

Among all of those is `npm` itself, by the way.

Both if the package is installed locally and globally, it makes sense to check for updates in order to let the user know if there's a new one, so that it's always up-to-date in case there was an important update released.

Currently, there is no way to disable this as we haven't received any other complaints yet, but I think it might actually be a great idea to provide some kind of environment flag for that. 👍 

Closing this, however, as that would be something for [update-check](https://github.com/zeit/update-check) itself.

Thank you for your feedback!

**Comment by leeyeh** [comment]
Here is another complaint. 😂 

Notifications about a newer version helps, however, this is not always the case when the package is used as a dependency.

For the users of my project, they do not know which package I'm using or how I use it to serve files. The update notification does not make  too much sense for them.

As the project author, I prefer to stick to a working version (using a package-lock.json to keep everything consistent) and use some dependency monitor services (i.e snyk.io) to keep myself notified with some important security updates.

`serve` is not a CLI for a service (like `npm`), a working version is good enough for me.
