### ISSUE TITLE
Has HTTPS been removed?

### ISSUE THREAD

**Issue by mhutti1** [zeit/serve#390]
I am trying to use this to host a server however I need to use HTTPS and it seems that this is no longer possible in the latest version so I have had to downgrade. Is this the case and if not is there any documentation on how to use it?

**Comment by leo** [comment]
👋 

We decided to drop HTTPS support from the core of the package, since there are just too many variants to support and getting it proper is difficult.

Aside of that, your `serve` instance should at least have some form of load balancer or proxy on top, otherwise what will happen if `serve` crashes/goes down?

However, as you can see [here](https://github.com/zeit/serve#api) adding the new middleware to a HTTPS server only takes one line:

```js
await handler(request, response);
```

In turn, I suggest either putting your app behind an LB/proxy or create a `.js` file for the server.

**Comment by just-boris** [comment]
> In turn, I suggest either putting your app behind an LB/proxy or create a .js file for the server.

But how about local development use-cases. I use `serve` to simply host some static files locally. Also, it is preferred to do this via https, because of various reasons, very well described in [this thread by Kyle Simpson](https://twitter.com/getify/status/1023202051902373888).

Currently I have to stick with serve@6, but it doesn't seem future-proof. Does anyone know another package, that has necessary features and is easy to use as `serve`?

**Comment by CanRau** [comment]
I would enjoy https for local/dev like @just-boris, too 🙏
